v2.0.1

diff --git a/bin/vidulum-fetch-params b/bin/vidulum-fetch-params
--- a/bin/vidulum-fetch-params
+++ b/bin/vidulum-fetch-params
@@ -2,17 +2,49 @@
 
 set -eu
 
+
+
 # Create default vidulum.conf
 if [[ "$OSTYPE" == "darwin"* ]]; then
-  if [ ! -e "$HOME/Library/Application Support/Vidulum/vidulum.conf" ] ; then
+  if [ ! -e "$HOME/Library/Application Support/Vidulum/vidulum.conf" ]; then
     mkdir -p "$HOME/Library/Application Support/Vidulum"
     echo "server=1" > "$HOME/Library/Application Support/Vidulum/vidulum.conf"
+    echo "addnode=downloads.vidulum.app" >> "$HOME/Library/Application Support/Vidulum/vidulum.conf"
+    echo "rpcuser=username$(LC_CTYPE=C tr -dc A-Za-z0-9 < /dev/urandom | fold -w ${1:-32} | head -n 1)" >> "$HOME/Library/Application Support/Vidulum/vidulum.conf"
+    echo "rpcpassword=password$(LC_CTYPE=C tr -dc A-Za-z0-9 < /dev/urandom | fold -w ${1:-32} | head -n 1)" >> "$HOME/Library/Application Support/Vidulum/vidulum.conf"
+    echo "daemon=0" >> "$HOME/Library/Application Support/Vidulum/vidulum.conf"
+    echo "txindex=1" >> "$HOME/Library/Application Support/Vidulum/vidulum.conf"
+    echo "showmetrics=1" >> "$HOME/Library/Application Support/Vidulum/vidulum.conf"
+    echo "gen=0" >> "$HOME/Library/Application Support/Vidulum/vidulum.conf"
   fi
-else
-  if [ ! -e "$HOME/.vidulum/vidulum.conf" ] ; then
-    mkdir -p "$HOME/.vidulum" 
+fi
+
+if [ ! -e "$HOME/Library/Application Support/Vidulum/masternode.conf" ]; then
+    mkdir -p "$HOME/Library/Application Support/Vidulum"
+    echo "# Masternode config file" > "$HOME/Library/Application Support/Vidulum/masternode.conf"
+fi
+
+if [ -e "$HOME/Library/Application Support/Vidulum/wallet.dat" ]; then
+    cp "$HOME/Library/Application Support/Vidulum/wallet.dat" "$HOME/Library/Application Support/Vidulum/wallet.dat.backup.Vidulum-Desktop-Wallet"
+elif [ ! -e "$HOME/.vidulum/vidulum.conf" ]; then
+    mkdir -p "$HOME/.vidulum"
     echo "server=1" > "$HOME/.vidulum/vidulum.conf"
-  fi
+    echo "addnode=downloads.vidulum.app" >> "$HOME/.vidulum/vidulum.conf"
+    echo "rpcuser=username$(LC_CTYPE=C tr -dc A-Za-z0-9 < /dev/urandom | fold -w ${1:-32} | head -n 1)" >> "$HOME/.vidulum/vidulum.conf"
+    echo "rpcpassword=password$(LC_CTYPE=C tr -dc A-Za-z0-9 < /dev/urandom | fold -w ${1:-32} | head -n 1)" >> "$HOME/.vidulum/vidulum.conf"
+    echo "daemon=0" >> "$HOME/.vidulum/vidulum.conf"
+    echo "txindex=1" >> "$HOME/.vidulum/vidulum.conf"
+    echo "showmetrics=1" >> "$HOME/.vidulum/vidulum.conf"
+    echo "gen=0" >> "$HOME/.vidulum/vidulum.conf"
+fi
+
+if [ ! -e "$HOME/.vidulum/masternode.conf" ]; then
+    mkdir -p "$HOME/.vidulum"
+    echo "# Masternode config file" > "$HOME/.vidulum//masternode.conf"
+fi
+
+if [ -e "$HOME/.vidulum/wallet.dat" ]; then
+    cp -p "$HOME/.vidulum/wallet.dat" "$HOME/.vidulum/wallet.dat.backup.Vidulum-Desktop-Wallet"
 fi
 
 if [[ "$OSTYPE" == "darwin"* ]]; then
@@ -26,8 +58,8 @@ SPROUT_VKEY_NAME='sprout-verifying.key'
 SAPLING_SPEND_NAME='sapling-spend.params'
 SAPLING_OUTPUT_NAME='sapling-output.params'
 SAPLING_SPROUT_GROTH16_NAME='sprout-groth16.params'
-SPROUT_URL="https://z.cash/downloads"
-SPROUT_IPFS="/ipfs/QmZKKx7Xup7LiAtFRhYsE1M7waXcv9ir9eCECyXAFGxhEo"
+SPROUT_URL="https://github.com/vidulum/sapling-params/releases/tag/sapling"
+SPROUT_IPFS="/ipfs/QmUSFo5zgPPXXejidzFWZcxVyF3AJH6Pr9br6Xisdww1r1"
 
 SHA256CMD="$(command -v sha256sum || echo shasum)"
 SHA256ARGS="$(command -v sha256sum >/dev/null || echo '-a 256')"
@@ -117,8 +149,21 @@ function fetch_params {
     local output="$2"
     local dlname="${output}.dl"
     local expectedhash="$3"
+    local shouldDownload=true
 
-    if ! [ -f "$output" ]
+    if [ -f "$output" ]; then
+        "$SHA256CMD" $SHA256ARGS -c <<EOF
+$expectedhash  $output
+EOF
+
+        # Check the exit code of the shasum command:
+        CHECKSUM_RESULT=$?
+        if [ $CHECKSUM_RESULT -eq 0 ]; then
+            shouldDownload=false
+        fi
+    fi
+
+    if [ "$shouldDownload"  = true ]
     then
         for method in wget ipfs curl failure; do
             if "fetch_$method" "$filename" "$dlname"; then
